/* generated by Svelte v3.20.0 */
import {
	SvelteElement,
	add_location,
	append_dev,
	detach_dev,
	dispatch_dev,
	element,
	init,
	insert_dev,
	noop,
	safe_not_equal,
	validate_slots
} from "svelte/internal";

import Title from "./Title.js";
const file = undefined;

function create_fragment(ctx) {
	let main;
	let ui_title;

	const block = {
		c: function create() {
			main = element("main");
			ui_title = element("ui-title");
			this.c = noop;
			add_location(ui_title, file, 23, 2, 377);
			add_location(main, file, 22, 0, 367);
		},
		l: function claim(nodes) {
			throw new Error("options.hydrate only works if the component was compiled with the `hydratable: true` option");
		},
		m: function mount(target, anchor) {
			insert_dev(target, main, anchor);
			append_dev(main, ui_title);
		},
		p: noop,
		i: noop,
		o: noop,
		d: function destroy(detaching) {
			if (detaching) detach_dev(main);
		}
	};

	dispatch_dev("SvelteRegisterBlock", {
		block,
		id: create_fragment.name,
		type: "component",
		source: "",
		ctx
	});

	return block;
}

function instance($$self, $$props, $$invalidate) {
	const writable_props = [];

	Object.keys($$props).forEach(key => {
		if (!~writable_props.indexOf(key) && key.slice(0, 2) !== "$$") console.warn(`<ui-app> was created with unknown prop '${key}'`);
	});

	let { $$slots = {}, $$scope } = $$props;
	validate_slots("ui-app", $$slots, []);
	$$self.$capture_state = () => ({ Title });
	return [];
}

class Component extends SvelteElement {
	constructor(options) {
		super();
		this.shadowRoot.innerHTML = `<style>main{position:fixed;top:0;left:0;width:100vw;height:100vh;display:flex;justify-content:center;align-items:center;flex-direction:column;color:white;font-size:1.125rem}</style>`;
		init(this, { target: this.shadowRoot }, instance, create_fragment, safe_not_equal, {});

		if (options) {
			if (options.target) {
				insert_dev(options.target, this, options.anchor);
			}
		}
	}
}

customElements.define("ui-app", Component);
export default Component;